import { Skeleton } from '@/components/ui/skeleton';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ArrowDown, ArrowUp, MoreHorizontal, Pencil, Plus, Trash2, ReceiptText } from 'lucide-react';
import type { Transaction } from '../../../types/transaction';
import { TypeBadge } from './TypeBadge';
import { signedMoney } from '../../../utils/format-money';
import { formatDate } from '../../../utils/format-date';
import { Button } from '@/components/ui/button';
function RowActions({ transaction, onEdit, onDelete }: { transaction: Transaction; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void }) {
  return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="plain" aria-label={`Ações para ${transaction.description || 'Sem descrição'}`} className="grid size-11 place-items-center rounded-lg text-muted hover:bg-brand-soft hover:text-brand" onClick={event => event.stopPropagation()}><MoreHorizontal size={19} /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={0} onClick={event => event.stopPropagation()}><DropdownMenuItem onSelect={() => onEdit(transaction)}><Pencil size={16} />Editar transação</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={() => onDelete(transaction)}><Trash2 size={16} />Excluir transação</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}

interface Props { data: Transaction[]; selectedId: string; sortOrder: 'asc' | 'desc'; loading: boolean; onSort: () => void; onSelect: (id: string) => void; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void; onClear: () => void; onCreate: () => void; canCreate: boolean; filtered: boolean }
export function TransactionsTable({ data, selectedId, sortOrder, loading, onSort, onSelect, onEdit, onDelete, onClear, onCreate, canCreate, filtered }: Props) {
  const SortIcon = sortOrder === 'desc' ? ArrowDown : ArrowUp;
  if (loading) return <div role="status" aria-label="Carregando transações">{Array.from({ length: 8 }, (_, index) => <div key={index} className="flex h-16 items-center gap-8 border-b border-line px-5"><Skeleton className="h-3 w-1/6 rounded bg-canvas" /><Skeleton className="h-3 w-2/5 rounded bg-canvas" /><Skeleton className="ml-auto h-3 w-1/6 rounded bg-canvas" /></div>)}</div>;
  if (!data.length) return <div className="flex min-h-[330px] flex-col items-center justify-center px-5 py-12 text-center"><ReceiptText size={32} strokeWidth={1.4} className="text-brand" /><h2 className="mt-5 text-xl font-semibold">{filtered ? 'Nenhuma transação encontrada' : 'Sua movimentação começa aqui'}</h2><p className="mt-2 mb-6 max-w-[42ch] text-sm leading-6 text-muted">{filtered ? 'Ajuste o período ou os filtros para encontrar o que procura.' : 'Registre sua primeira venda, compra ou despesa para acompanhar o saldo.'}</p><div className="flex flex-wrap justify-center gap-3">{filtered && <Button onClick={onClear}>Limpar filtros</Button>}<Button variant="primary" onClick={onCreate} disabled={!canCreate}><Plus />Adicionar transação</Button></div></div>;
  return <><div className="@max-[740px]:hidden"><Table className="w-full table-fixed border-collapse text-sm"><TableHeader className="bg-canvas/60 text-[11px] font-medium text-muted"><TableRow><TableHead className="w-[156px] px-5 text-left font-medium" aria-sort={sortOrder === 'desc' ? 'descending' : 'ascending'}><Button variant="plain" type="button" onClick={onSort} className="flex min-h-11 items-center gap-2">Data<SortIcon size={14} /></Button></TableHead><TableHead className="px-3 text-left font-medium">Descrição</TableHead><TableHead className="w-[22%] px-3 text-left font-medium">Fornecedor</TableHead><TableHead className="w-[126px] px-3 text-left font-medium">Tipo</TableHead><TableHead className="w-[140px] px-3 text-right font-medium">Valor</TableHead><TableHead className="w-[56px]"><span className="sr-only">Ações</span></TableHead></TableRow></TableHeader><TableBody>{data.map(transaction => <TableRow key={transaction.id} onClick={() => onSelect(transaction.id)} className={`cursor-pointer border-t border-line transition-colors ${selectedId === transaction.id ? 'bg-brand-soft' : 'hover:bg-canvas/70'}`}><TableCell className="numeric px-5 py-4 text-xs whitespace-nowrap text-muted">{formatDate(transaction.transactionDate)}</TableCell><TableCell className="px-3 py-4"><Button variant="plain" type="button" data-transaction-trigger={transaction.id} title={transaction.description || 'Sem descrição'} className="block min-h-8 w-full truncate text-left font-medium leading-5" aria-pressed={selectedId === transaction.id} onClick={event => { event.stopPropagation(); onSelect(transaction.id); }}>{transaction.description || 'Sem descrição'}</Button></TableCell><TableCell className="px-3 py-4 text-xs text-muted"><span className="block truncate" title={transaction.supplier?.name}>{transaction.supplier?.name || 'Sem fornecedor'}</span></TableCell><TableCell className="px-3 py-4"><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /></TableCell><TableCell className={`numeric px-3 py-4 text-right text-sm font-medium whitespace-nowrap ${transaction.transactionType.code === 'sale' ? 'text-sale' : transaction.transactionType.code === 'purchase' ? 'text-purchase' : 'text-expense'}`}>{signedMoney(transaction.amount, transaction.transactionType.code)}</TableCell><TableCell className="py-2 pr-2"><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></TableCell></TableRow>)}</TableBody></Table></div>
    <div className="hidden @max-[740px]:block"><div className="flex justify-end border-b border-line px-4"><Button variant="plain" type="button" className="flex min-h-11 items-center gap-2 text-xs text-muted" onClick={onSort}>Data<SortIcon size={14} /></Button></div>{data.map(transaction => <article key={transaction.id} className={`flex min-w-0 items-start gap-1 border-b border-line px-3 last:border-b-0 ${selectedId === transaction.id ? 'bg-brand-soft' : ''}`}><Button variant="plain" type="button" data-transaction-trigger={transaction.id} className="min-w-0 flex-1 py-4 pr-1 text-left" aria-pressed={selectedId === transaction.id} onClick={() => onSelect(transaction.id)}><span className="flex flex-wrap items-start justify-between gap-x-4 gap-y-2 text-sm"><span className="min-w-0 flex-1 font-medium leading-5"><span className="block truncate" title={transaction.description || 'Sem descrição'}>{transaction.description || 'Sem descrição'}</span>{transaction.supplier && <small className="mt-1 block truncate text-xs font-normal text-muted">{transaction.supplier.name}</small>}</span><strong className={`numeric text-sm font-semibold whitespace-nowrap ${transaction.transactionType.code === 'sale' ? 'text-sale' : transaction.transactionType.code === 'purchase' ? 'text-purchase' : 'text-expense'}`}>{signedMoney(transaction.amount, transaction.transactionType.code)}</strong></span><span className="mt-3 flex flex-wrap items-center justify-between gap-2"><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /><span className="numeric text-xs text-muted">{formatDate(transaction.transactionDate)}</span></span></Button><div className="pt-2"><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></div></article>)}</div>
  </>;
}
