import { useEffect, useRef } from 'react';
import { ArrowDown, ArrowUp, MoreHorizontal, Pencil, Plus, Trash2, ReceiptText } from 'lucide-react';
import type { Transaction } from '../../../types/transaction';
import { TypeBadge } from './TypeBadge';
import { signedMoney } from '../../../utils/format-money';
import { formatDate } from '../../../utils/format-date';
import { Button } from '../../../components/atom/Button';
function RowActions({ transaction, onEdit, onDelete }: { transaction: Transaction; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void }) {
  const ref = useRef<HTMLDetailsElement>(null);
  useEffect(() => { const close = (event: Event) => { if (ref.current?.open && event.target instanceof Node && !ref.current.contains(event.target)) ref.current.open = false; }; document.addEventListener('pointerdown', close); document.addEventListener('focusin', close); return () => { document.removeEventListener('pointerdown', close); document.removeEventListener('focusin', close); }; }, []);
  return <details ref={ref} className="relative" onClick={event => event.stopPropagation()} onKeyDown={event => { if (event.key === 'Escape') { event.preventDefault(); ref.current!.open = false; ref.current?.querySelector('summary')?.focus(); } }}><summary aria-label={`Ações para ${transaction.description || 'Sem descrição'}`} className="grid size-11 cursor-pointer list-none place-items-center rounded-lg text-muted hover:bg-brand-soft hover:text-brand [&::-webkit-details-marker]:hidden"><MoreHorizontal size={19} /></summary><div className="absolute top-11 right-0 z-20 min-w-[190px] rounded-xl bg-white p-1.5 shadow-layer"><button type="button" className="flex min-h-11 w-full items-center gap-2 rounded-lg px-3 text-left text-sm hover:bg-canvas" onClick={() => { if (ref.current) ref.current.open = false; onEdit(transaction); }}><Pencil size={16} />Editar transação</button><button type="button" className="flex min-h-11 w-full items-center gap-2 rounded-lg px-3 text-left text-sm text-expense hover:bg-[#fcedf0]" onClick={() => { if (ref.current) ref.current.open = false; onDelete(transaction); }}><Trash2 size={16} />Excluir transação</button></div></details>;
}
interface Props { data: Transaction[]; selectedId: string; sortOrder: 'asc' | 'desc'; loading: boolean; onSort: () => void; onSelect: (id: string) => void; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void; onClear: () => void; onCreate: () => void; canCreate: boolean; filtered: boolean }
export function TransactionsTable({ data, selectedId, sortOrder, loading, onSort, onSelect, onEdit, onDelete, onClear, onCreate, canCreate, filtered }: Props) {
  const SortIcon = sortOrder === 'desc' ? ArrowDown : ArrowUp;
  if (loading) return <div role="status" aria-label="Carregando transações">{Array.from({ length: 8 }, (_, index) => <div key={index} className="flex h-16 items-center gap-8 border-b border-line px-5"><span className="h-3 w-1/6 rounded bg-canvas" /><span className="h-3 w-2/5 rounded bg-canvas" /><span className="ml-auto h-3 w-1/6 rounded bg-canvas" /></div>)}</div>;
  if (!data.length) return <div className="flex min-h-[330px] flex-col items-center justify-center px-5 py-12 text-center"><ReceiptText size={32} strokeWidth={1.4} className="text-brand" /><h2 className="mt-5 text-xl font-semibold">{filtered ? 'Nenhuma transação encontrada' : 'Sua movimentação começa aqui'}</h2><p className="mt-2 mb-6 max-w-[42ch] text-sm leading-6 text-muted">{filtered ? 'Ajuste o período ou os filtros para encontrar o que procura.' : 'Registre sua primeira venda, compra ou despesa para acompanhar o saldo.'}</p><div className="flex flex-wrap justify-center gap-3">{filtered && <Button onClick={onClear}>Limpar filtros</Button>}<Button variant="primary" onClick={onCreate} disabled={!canCreate}><Plus />Adicionar transação</Button></div></div>;
  return <><div className="@max-[740px]:hidden"><table className="w-full table-fixed border-collapse text-sm"><thead className="bg-canvas/60 text-[11px] font-medium text-muted"><tr><th className="w-[156px] px-5 text-left font-medium" aria-sort={sortOrder === 'desc' ? 'descending' : 'ascending'}><button type="button" onClick={onSort} className="flex min-h-11 items-center gap-2">Data<SortIcon size={14} /></button></th><th className="px-3 text-left font-medium">Descrição</th><th className="w-[22%] px-3 text-left font-medium">Fornecedor</th><th className="w-[126px] px-3 text-left font-medium">Tipo</th><th className="w-[140px] px-3 text-right font-medium">Valor</th><th className="w-[56px]"><span className="sr-only">Ações</span></th></tr></thead><tbody>{data.map(transaction => <tr key={transaction.id} onClick={() => onSelect(transaction.id)} className={`cursor-pointer border-t border-line transition-colors ${selectedId === transaction.id ? 'bg-brand-soft' : 'hover:bg-canvas/70'}`}><td className="numeric px-5 py-4 text-xs whitespace-nowrap text-muted">{formatDate(transaction.transactionDate)}</td><td className="px-3 py-4"><button type="button" data-transaction-trigger={transaction.id} title={transaction.description || 'Sem descrição'} className="block min-h-8 w-full truncate text-left font-medium leading-5" aria-pressed={selectedId === transaction.id} onClick={event => { event.stopPropagation(); onSelect(transaction.id); }}>{transaction.description || 'Sem descrição'}</button></td><td className="px-3 py-4 text-xs text-muted"><span className="block truncate" title={transaction.supplier?.name}>{transaction.supplier?.name || 'Sem fornecedor'}</span></td><td className="px-3 py-4"><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /></td><td className={`numeric px-3 py-4 text-right text-sm font-medium whitespace-nowrap ${transaction.transactionType.code === 'sale' ? 'text-sale' : transaction.transactionType.code === 'purchase' ? 'text-purchase' : 'text-expense'}`}>{signedMoney(transaction.amount, transaction.transactionType.code)}</td><td className="py-2 pr-2"><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></td></tr>)}</tbody></table></div>
    <div className="hidden @max-[740px]:block"><div className="flex justify-end border-b border-line px-4"><button type="button" className="flex min-h-11 items-center gap-2 text-xs text-muted" onClick={onSort}>Data<SortIcon size={14} /></button></div>{data.map(transaction => <article key={transaction.id} className={`flex min-w-0 items-start gap-1 border-b border-line px-3 last:border-b-0 ${selectedId === transaction.id ? 'bg-brand-soft' : ''}`}><button type="button" data-transaction-trigger={transaction.id} className="min-w-0 flex-1 py-4 pr-1 text-left" aria-pressed={selectedId === transaction.id} onClick={() => onSelect(transaction.id)}><span className="flex flex-wrap items-start justify-between gap-x-4 gap-y-2 text-sm"><span className="min-w-0 flex-1 font-medium leading-5"><span className="block truncate" title={transaction.description || 'Sem descrição'}>{transaction.description || 'Sem descrição'}</span>{transaction.supplier && <small className="mt-1 block truncate text-xs font-normal text-muted">{transaction.supplier.name}</small>}</span><strong className={`numeric text-sm font-semibold whitespace-nowrap ${transaction.transactionType.code === 'sale' ? 'text-sale' : transaction.transactionType.code === 'purchase' ? 'text-purchase' : 'text-expense'}`}>{signedMoney(transaction.amount, transaction.transactionType.code)}</strong></span><span className="mt-3 flex flex-wrap items-center justify-between gap-2"><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /><span className="numeric text-xs text-muted">{formatDate(transaction.transactionDate)}</span></span></button><div className="pt-2"><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></div></article>)}</div>
  </>;
}
