import { useRef } from 'react';
import { ArrowDown, ArrowUp, MoreHorizontal, Pencil, Trash2, ReceiptText } from 'lucide-react';
import type { Transaction } from '../../../types/transaction';
import { TypeBadge } from './TypeBadge';
import { signedMoney } from '../../../utils/format-money';
import { formatDate } from '../../../utils/format-date';
import { Button } from '../../../components/atom/Button';
const classes = {
  "actions": "relative [&_summary]:grid [&_summary]:h-11 [&_summary]:w-[38px] [&_summary]:cursor-pointer [&_summary]:list-none [&_summary]:place-items-center [&_summary]:rounded-[5px] [&_summary]:text-[#25324b] [&_summary]:hover:bg-[#efe9ed] [&_summary::-webkit-details-marker]:hidden [&>div]:absolute [&>div]:top-[42px] [&>div]:right-1.5 [&>div]:z-6 [&>div]:min-w-[184px] [&>div]:rounded-md [&>div]:bg-white [&>div]:p-1.5 [&>div]:shadow-layer [&>div_button]:flex [&>div_button]:min-h-11 [&>div_button]:w-full [&>div_button]:items-center [&>div_button]:gap-[9px] [&>div_button]:border-0 [&>div_button]:bg-white [&>div_button]:p-2.5 [&>div_button]:text-left [&>div_button]:text-[13px] [&>div_button]:text-[#26334a] [&>div_button]:hover:bg-[#f8f1f3] [&>div_button:last-child]:text-expense",
  "loading": "[&>div]:flex [&>div]:h-14 [&>div]:items-center [&>div]:gap-10 [&>div]:border-b [&>div]:border-line [&>div]:px-[22px] [&_span]:h-3.5 [&_span]:w-[20%] [&_span]:rounded [&_span]:bg-[#f1f1f4] [&_span:nth-child(2)]:w-[45%]",
  "empty": "flex min-h-[340px] flex-col items-center justify-center px-5 py-12 text-center text-muted [&>svg]:text-brand [&_h2]:mt-5 [&_h2]:mb-2 [&_h2]:text-xl [&_h2]:font-medium [&_h2]:text-ink [&_p]:mb-5 [&_p]:max-w-[40ch] [&_p]:text-sm [&_p]:leading-[1.7]",
  "tableWrap": "w-full max-[900px]:hidden",
  "table": "w-full table-fixed border-separate border-spacing-0 text-[13px] [&_th]:h-12 [&_th]:px-[22px] [&_th]:pt-3 [&_th]:pb-4 [&_th]:text-left [&_th]:font-medium [&_th]:text-[#161d30] [&_th:first-child]:w-[15%] [&_th:nth-child(2)]:w-[42%] [&_th:nth-child(3)]:w-[18%] [&_th:nth-child(4)]:w-[20%] [&_th:last-child]:w-[5%] [&_th:last-child]:p-0 [&_th_button]:flex [&_th_button]:items-center [&_th_button]:gap-2.5 [&_th_button]:border-0 [&_th_button]:bg-transparent [&_th_button]:p-0 [&_td]:h-14 [&_td]:border-b [&_td]:border-[#ececf0] [&_td]:px-[22px] [&_td]:py-2.5 [&_td]:text-[#414b61] [&_tr]:cursor-pointer [&_tr:hover_td]:bg-[#faf8f9] [&_td:first-child]:relative [&_td:last-child]:p-0 min-[1440px]:max-[1550px]:[&_th]:px-[15px] min-[1440px]:max-[1550px]:[&_td]:px-[15px] min-[1440px]:max-[1550px]:[&_th:first-child]:w-[17%] min-[1440px]:max-[1550px]:[&_th:nth-child(2)]:w-[37%] min-[1440px]:max-[1550px]:[&_th:nth-child(4)]:w-[23%]",
  "amountHead": "!text-right",
  "date": "whitespace-nowrap text-xs",
  "description": "[&_button]:border-0 [&_button]:bg-transparent [&_button]:p-0 [&_button]:text-left [&_button]:leading-[1.6] [&_button]:[overflow-wrap:anywhere]",
  "supplier": "mt-0.5 block overflow-hidden text-ellipsis whitespace-nowrap text-[11px] leading-[1.4] text-muted",
  "amount": "!pr-5 !text-right text-sm whitespace-nowrap [font-variant-numeric:tabular-nums]",
  "sale": "!text-sale",
  "purchase": "!text-expense",
  "expense": "!text-expense",
  "selected": "[&_td]:!border-[#f0e8ea] [&_td]:!bg-[#f8f0f2] [&_td:first-child]:before:absolute [&_td:first-child]:before:inset-y-0 [&_td:first-child]:before:left-0 [&_td:first-child]:before:w-[3px] [&_td:first-child]:before:bg-brand max-[900px]:rounded-[5px] max-[900px]:bg-[#f8f0f2]",
  "mobileList": "hidden max-[900px]:block",
  "mobileSort": "flex justify-end px-2 pb-2 [&_button]:flex [&_button]:min-h-8 [&_button]:items-center [&_button]:gap-2 [&_button]:border-0 [&_button]:bg-transparent [&_button]:text-xs [&_button]:text-muted",
  "mobileRow": "relative flex min-w-0 items-center border-b border-line [&_.row-actions]:mt-[9px] [&_.row-actions]:self-start",
  "mobileSelect": "min-w-0 flex-1 border-0 bg-transparent py-[17px] pr-0 pl-2.5 text-left text-[#323b50]",
  "mobileTop": "flex items-start justify-between gap-3 text-[13px] leading-[1.6] max-[360px]:flex-wrap [&>span]:min-w-0 [&>span]:[overflow-wrap:anywhere] [&_strong]:shrink-0 [&_strong]:text-[13px] [&_strong]:font-medium [&_strong]:[font-variant-numeric:tabular-nums]",
  "mobileBottom": "mt-3 flex items-center justify-between gap-3 [&>span:last-child]:text-[11px] [&>span:last-child]:text-muted"
} as Record<string, string>;
function RowActions({ transaction, onEdit, onDelete }: { transaction: Transaction; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void }) {
 const ref = useRef<HTMLDetailsElement>(null);
 return <details ref={ref} className={`${classes.actions} row-actions`} onClick={e => e.stopPropagation()} onKeyDown={e => { if(e.key === 'Escape') { e.currentTarget.open = false; e.currentTarget.querySelector('summary')?.focus() } }}><summary aria-label={`Ações para ${transaction.description}`}><MoreHorizontal size={20} /></summary><div><button onClick={() => { if(ref.current) ref.current.open = false; onEdit(transaction) }}><Pencil size={16} />Editar transação</button><button onClick={() => { if(ref.current) ref.current.open = false; onDelete(transaction) }}><Trash2 size={16} />Excluir transação</button></div></details>;
}
interface Props { data: Transaction[]; selectedId: string; sortOrder: 'asc' | 'desc'; loading: boolean; onSort: () => void; onSelect: (id: string, trigger?: HTMLElement) => void; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void; onClear: () => void; filtered: boolean }
export function TransactionsTable({ data, selectedId, sortOrder, loading, onSort, onSelect, onEdit, onDelete, onClear, filtered }: Props) {
 const SortIcon = sortOrder === 'desc' ? ArrowDown : ArrowUp;
 if (loading) return <div className={classes.loading} role="status" aria-label="Carregando transações">{Array.from({ length: 8 }, (_, i) => <div key={i}><span /><span /><span /></div>)}</div>;
 if (!data.length) return <div className={classes.empty}><ReceiptText size={34} strokeWidth={1.3} /><h2>{filtered ? 'Nenhuma transação encontrada' : 'Um novo começo'}</h2><p>{filtered ? 'Tente outro mês, tipo, fornecedor ou pesquisa.' : 'Sua movimentação financeira aparecerá aqui. Adicione sua primeira transação para começar.'}</p>{filtered && <Button onClick={onClear}>Limpar filtros</Button>}</div>;
 return <><div className={classes.tableWrap}><table className={classes.table}><thead><tr><th aria-sort={sortOrder === 'desc' ? 'descending' : 'ascending'}><button onClick={onSort}>Data<SortIcon size={16} /></button></th><th>Descrição</th><th>Tipo</th><th className={classes.amountHead}>Valor</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{data.map(transaction => <tr key={transaction.id} className={selectedId === transaction.id ? classes.selected : ''} onClick={() => onSelect(transaction.id)}><td className={classes.date}>{formatDate(transaction.transactionDate)}</td><td className={classes.description}><button data-transaction-trigger={transaction.id} onClick={e => { e.stopPropagation(); onSelect(transaction.id, e.currentTarget) }} aria-pressed={selectedId === transaction.id}>{transaction.description}</button>{transaction.supplier && <span className={classes.supplier}>{transaction.supplier.name}</span>}</td><td><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /></td><td className={`${classes.amount} ${classes[transaction.transactionType.code]}`}>{signedMoney(transaction.amount, transaction.transactionType.code)}</td><td><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></td></tr>)}</tbody></table></div>
 <div className={classes.mobileList}><div className={classes.mobileSort}><button onClick={onSort}>Data<SortIcon size={16} /></button></div>{data.map(transaction => <article key={transaction.id} className={`${classes.mobileRow} ${selectedId === transaction.id ? classes.selected : ''}`}><button data-transaction-trigger={transaction.id} className={classes.mobileSelect} aria-pressed={selectedId === transaction.id} onClick={e => onSelect(transaction.id, e.currentTarget)}><span className={classes.mobileTop}><span>{transaction.description}{transaction.supplier && <small className={classes.supplier}>{transaction.supplier.name}</small>}</span><strong className={classes[transaction.transactionType.code]}>{signedMoney(transaction.amount, transaction.transactionType.code)}</strong></span><span className={classes.mobileBottom}><TypeBadge code={transaction.transactionType.code} name={transaction.transactionType.name} deletedAt={transaction.transactionType.deletedAt} /><span>{formatDate(transaction.transactionDate)}</span></span></button><RowActions transaction={transaction} onEdit={onEdit} onDelete={onDelete} /></article>)}</div></>;
}
