import type { TransactionDto, TransactionInputDto, TransactionPageDto, TransactionQueryDto, TransactionTypeDto } from '../dto/transaction.dto';
import type { Transaction, TransactionInput, TransactionPage, TransactionFilters, TransactionType } from '../../types/transaction';
export function toTransactionType(dto: TransactionTypeDto): TransactionType { return { id: dto.id, code: dto.code, name: dto.name, deletedAt: dto.deleted_at ?? null } }
export function toTransaction(dto: TransactionDto): Transaction {
 return { id: dto.id, transactionTypeId: dto.transaction_type_id, transactionType: toTransactionType(dto.transaction_type), supplierId: dto.supplier_id, supplier: dto.supplier ? { id: dto.supplier.id, name: dto.supplier.name, deletedAt: dto.supplier.deleted_at ?? null } : null, amount: dto.amount, currency: dto.currency, transactionDate: dto.transaction_date, description: dto.description, reference: dto.reference, notes: dto.notes, version: dto.version, deletedAt: dto.deleted_at ?? null, createdAt: dto.created_at, updatedAt: dto.updated_at };
}
export function toTransactionPage(dto: TransactionPageDto): TransactionPage { return { data: dto.data.map(toTransaction), meta: { page: dto.meta.page, pageSize: dto.meta.page_size, total: dto.meta.total, totalPages: dto.meta.total_pages }, summary: dto.summary } }
export function toTransactionPayload(input: TransactionInput): TransactionInputDto { return { transaction_type_id: input.transactionTypeId, supplier_id: input.supplierId, amount: input.amount, currency: input.currency, transaction_date: input.transactionDate, description: input.description, reference: input.reference, notes: input.notes } }
export function toTransactionQuery(filter: TransactionFilters): TransactionQueryDto { return { date_from: filter.dateFrom || undefined, date_to: filter.dateTo || undefined, transaction_type_id: filter.transactionTypeId || undefined, supplier_id: filter.supplierId || undefined, search: filter.search || undefined, sort_order: filter.sortOrder, page: filter.page, page_size: filter.pageSize } }
